Repository curveball/aws-lambda, pull requests merged in 2020-03, with the labels that each got.

#15 target to es2019
  changelog.md
  tsconfig.json
Labels: enhancement

#17 Docs: use handler default import
  README.md
Labels: bug

#21 Update dependencies + settings
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies
